server_names = [
  'cs-de',
  'cs-berlin',
  'cs-nl',
  'cs-belgium',
  'cs-ch',
  'cs-barcelona',
  'cs-milan',
  'cs-austria',
  'cs-czech',
  'cs-poland',
  'cs-hungary',
  'cs-ro',
  'cs-serbia',
  
  'cs-fr',
  'cs-dus',
  'cs-london',
  'cs-manchester',
  'cs-swe',
  'cs-norway',
  'cs-finland',
  'cs-pt',
  'cs-md',
  
  'digitalprivacy.diy-dnscrypt-ipv4',
  'dct-de',
  'dct-fr',
  
  'dnscry.pt-amsterdam-ipv4',
  'dnscry.pt-amsterdam02-ipv4',
  'dnscry.pt-amsterdam03-ipv4',
  'dnscry.pt-athens-ipv4',
  'dnscry.pt-barcelona-ipv4',
  'dnscry.pt-bratislava-ipv4',
  'dnscry.pt-brussels-ipv4',
  'dnscry.pt-bucharest-ipv4',
  'dnscry.pt-budapest-ipv4',
  'dnscry.pt-chisinau-ipv4',
  'dnscry.pt-copenhagen-ipv4',
  'dnscry.pt-coventry-ipv4',
  'dnscry.pt-dublin-ipv4',
  'dnscry.pt-dusseldorf-ipv4',
  'dnscry.pt-eygelshoven-ipv4',
  'dnscry.pt-frankfurt-ipv4',
  'dnscry.pt-frankfurt02-ipv4',
  'dnscry.pt-gdansk-ipv4',
  'dnscry.pt-geneva-ipv4',
  'dnscry.pt-helsinki-ipv4',
  'dnscry.pt-jena-ipv4',
  'dnscry.pt-kyiv-ipv4',
  'dnscry.pt-kyiv02-ipv4',
  'dnscry.pt-lisbon-ipv4',
  'dnscry.pt-lisbon02-ipv4',
  'dnscry.pt-ljubljana-ipv4',
  'dnscry.pt-london-ipv4',
  'dnscry.pt-luxembourg-ipv4',
  'dnscry.pt-madrid-ipv4',
  'dnscry.pt-manchester-ipv4',
  'dnscry.pt-marseille-ipv4',
  'dnscry.pt-milan-ipv4',
  'dnscry.pt-molln-ipv4',
  'dnscry.pt-munich-ipv4',
  'dnscry.pt-naaldwijk-ipv4',
  'dnscry.pt-newcastle-ipv4',
  'dnscry.pt-nuremberg-ipv4',
  'dnscry.pt-oradea-ipv4',
  'dnscry.pt-palermo-ipv4',
  'dnscry.pt-paris-ipv4',
  'dnscry.pt-prague-ipv4',
  'dnscry.pt-redditch-ipv4',
  'dnscry.pt-riga-ipv4',
  'dnscry.pt-sandefjord-ipv4',
  'dnscry.pt-sofia-ipv4',
  'dnscry.pt-stockholm02-ipv4',
  'dnscry.pt-tallinn-ipv4',
  'dnscry.pt-zurich-ipv4'
]

listen_addresses = ['127.0.0.1:54', '[::1]:54']
max_clients = 250

ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = false
odoh_servers = false

require_dnssec = true
require_nolog = true
require_nofilter = true

disabled_server_names = [
  'cleanbrowsing-adult', 'cleanbrowsing-family', 'cleanbrowsing-security',
  'scaleway-fr', 'scaleway-ams',
  'dnscrypt.uk-ipv4', 'dnscrypt.uk-ipv6', 'v.dnscrypt.uk-ipv4', 'v.dnscrypt.uk-ipv6'
]

force_tcp = false
http3 = false
timeout = 5000
keepalive = 60

lb_strategy = 'p4'
lb_estimator = true

log_level = 2
use_syslog = true
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

cert_refresh_delay = 240
cert_ignore_timestamp = false
dnscrypt_ephemeral_keys = true
tls_disable_session_tickets = true

bootstrap_resolvers = ['9.9.9.9:53', '1.1.1.1:53', '8.8.8.8:53']
ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = '9.9.9.9:53'

block_ipv6 = false
block_unqualified = true
block_undelegated = true
reject_ttl = 10

cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

[captive_portals]

[local_doh]

[query_log]
format = 'tsv'

[nx_log]
format = 'tsv'

[blocked_names]

[blocked_ips]

[allowed_names]

[allowed_ips]

[schedules]

[sources]
  [sources.public-resolvers]
    urls = [
      'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
      'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md'
    ]
    cache_file = 'public-resolvers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''
  [sources.relays]
    urls = [
      'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md',
      'https://download.dnscrypt.info/resolvers-list/v3/relays.md'
    ]
    cache_file = 'relays.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''
  [sources.dnscry-pt-resolvers]
    urls = ['https://www.dnscry.pt/resolvers.md']
    minisign_key = 'RWQM31Nwkqh01x88SvrBL8djp1NH56Rb4mKLHz16K7qsXgEomnDv6ziQ'
    cache_file = 'dnscry.pt-resolvers.md'
    refresh_delay = 72
    prefix = 'dnscry.pt-'

[broken_implementations]

fragments_blocked = [
  'cisco',
  'cisco-ipv6',
  'cisco-familyshield',
  'cisco-familyshield-ipv6',
  'cisco-sandbox',
  'cleanbrowsing-adult',
  'cleanbrowsing-adult-ipv6',
  'cleanbrowsing-family',
  'cleanbrowsing-family-ipv6',
  'cleanbrowsing-security',
  'cleanbrowsing-security-ipv6'
]

[doh_client_x509_auth]

[anonymized_dns]
routes = [
  { server_name = '*', via = [
    'anon-scaleway',
    'anon-scaleway-ams',
    'anon-scaleway2',
    'anon-kama',
    
    'anon-ibksturm',
    'anon-dnswarden-swiss',
    
    'anon-dnscrypt.uk-ipv4',
    'anon-v.dnscrypt.uk-ipv4',
    
    'anon-serbica',
    'anon-digitalprivacy.diy-ipv4',
    
    'dnscry.pt-anon-amsterdam-ipv4',
    'dnscry.pt-anon-amsterdam02-ipv4',
    'dnscry.pt-anon-amsterdam03-ipv4',
    'dnscry.pt-anon-athens-ipv4',
    'dnscry.pt-anon-barcelona-ipv4',
    'dnscry.pt-anon-bratislava-ipv4',
    'dnscry.pt-anon-brussels-ipv4',
    'dnscry.pt-anon-bucharest-ipv4',
    'dnscry.pt-anon-budapest-ipv4',
    'dnscry.pt-anon-chisinau-ipv4',
    'dnscry.pt-anon-copenhagen-ipv4',
    'dnscry.pt-anon-coventry-ipv4',
    'dnscry.pt-anon-dublin-ipv4',
    'dnscry.pt-anon-dusseldorf-ipv4',
    'dnscry.pt-anon-eygelshoven-ipv4',
    'dnscry.pt-anon-frankfurt-ipv4',
    'dnscry.pt-anon-frankfurt02-ipv4',
    'dnscry.pt-anon-gdansk-ipv4',
    'dnscry.pt-anon-geneva-ipv4',
    'dnscry.pt-anon-helsinki-ipv4',
    'dnscry.pt-anon-jena-ipv4',
    'dnscry.pt-anon-kyiv-ipv4',
    'dnscry.pt-anon-kyiv02-ipv4',
    'dnscry.pt-anon-lisbon-ipv4',
    'dnscry.pt-anon-lisbon02-ipv4',
    'dnscry.pt-anon-ljubljana-ipv4',
    'dnscry.pt-anon-london-ipv4',
    'dnscry.pt-anon-luxembourg-ipv4',
    'dnscry.pt-anon-madrid-ipv4',
    'dnscry.pt-anon-manchester-ipv4',
    'dnscry.pt-anon-marseille-ipv4',
    'dnscry.pt-anon-milan-ipv4',
    'dnscry.pt-anon-molln-ipv4',
    'dnscry.pt-anon-munich-ipv4',
    'dnscry.pt-anon-naaldwijk-ipv4',
    'dnscry.pt-anon-newcastle-ipv4',
    'dnscry.pt-anon-nuremberg-ipv4',
    'dnscry.pt-anon-oradea-ipv4',
    'dnscry.pt-anon-palermo-ipv4',
    'dnscry.pt-anon-paris-ipv4',
    'dnscry.pt-anon-prague-ipv4',
    'dnscry.pt-anon-redditch-ipv4',
    'dnscry.pt-anon-riga-ipv4',
    'dnscry.pt-anon-sandefjord-ipv4',
    'dnscry.pt-anon-sofia-ipv4',
    'dnscry.pt-anon-stockholm02-ipv4',
    'dnscry.pt-anon-tallinn-ipv4',
    'dnscry.pt-anon-zurich-ipv4'
  ]}
]

skip_incompatible = false
direct_cert_fallback = true

[dns64]

[ip_encryption]
algorithm = "none"
key = ""

[monitoring_ui]
enabled = false

[static]
